apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-xeisgmtg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-xeisgmtg:1ee024e206d24d1753f314ecc95d5e4f67f5cd09@sha256:1922ebed4acb36d0813ba0d0065e72f6fb874040886f6b0d1c6769a0c9b7afd6
          name: container-image
